In [25]:
import numpy as np

# Vectors

# Define a finction to calculate dot product of two matrices
def dot_product(x,y):

# ensure that both the vectors have same length
    return sum(i*j for i,j in zip(x,y))

# The zip function pairs elements for the two sequences x and y together.
# For Example, if x =[1,2,3] abd y=[4,5,6], zip(x,y) will create an iteratot
# that produces tuples:
# (1,4),(2,5) and (3,6).


In [26]:
dot_product([3,4,5],[6,7,8])       #(3*6)+(4*7)+(5*8) = 86

86

In [27]:
# 1. Minor
# 2. Cofactor
# 3. Adjoint matrix

In [28]:
# matrix
# Eigenvalue and Eigenvectors
# Deferential Calculas
# inferitial calculas

In [29]:
# 1.Dot Product

# Explaination:

# The dot product of two vectors measure the simmilarity or projection
# of one vector onto another

# Use Case:
# Suppose you have vectors representing quantities sold for tow different
# product in a day for a store. Calulate the total revenue by taking the 
# dot product of the vectors representing quantities sold and unit
# price.

quantities_sold = np.array([20,30,40])
unit_prices = np.array([10,15,20])

In [30]:
import numpy as np

Total_revenue = np.dot(quantities_sold,unit_prices)
Total_revenue

np.int64(1450)

In [31]:
# 2. Cross Product

# Explaination:
# The cross product of tow vectors result in a vector that is perpendicular
# to both input vectors, useful in physics and engineering for calculating torque,
# magentic feilds etc.

# Use Case:
# Imagine calculating the torque exerted on a lever by using the cross product
# of force and lever arm vectors.

force = np.array([2,3,4])
lever_arm = np.array([0,1,0])    

In [32]:
torque = np.cross(force, lever_arm)
torque

array([-4,  0,  2])

In [33]:
# 3. Norm of a Vector

# Explaination:
# The norm(or magnitude) of a vector measures its length in Euclidean space,
# often used to quantify distance and sizes.

# Use Case:
# Calculate the speed of a moving object using its velocity vector's norm
velocity = np.array([3,4])

In [34]:
speed = np.linalg.norm(velocity)
speed

np.float64(5.0)

In [35]:
# 4. Addition of Matrices

# Explaination:
# Matrix addition involves adding corresponding elemments of matrices useful
# in aggrigation data and combining 

# Use case:
# Combine daily sales data from two different stores respresented as matrices
store1_sales = np.array([[100,120],[150,180]])
store2_sales = np.array([[80,90],[160,190]])

In [36]:
# print(np.add(store1_sales,store2_sales))

total_sales = store1_sales + store2_sales
print(total_sales)

[[180 210]
 [310 370]]


In [39]:
# 5. Multiplication of Matrix

# Emplaination: 
# matrix multiplication involves combining rows of the first matrix and columns of the
# second matrix, useful in transformation and linear mappings

# Use Case:
# Calculate the total cost matrix by multiplying price matrix with quantity sold
# matrix

prices = np.array([[10,15], [20,25]])
quanitites_sold = np.array([[100,120], [150,180]])

total = np.matmul(prices, quantities_sold)
total

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [40]:
# Transpose of a matrix Explaination:

# The transpose of a matrix flips it over its diagonal, useful in various
# operations such as finding orthogonal matrices

# Use case: Find the transpose of a matrix representing employee skills and
# preferences. 
a = np.array([[1,2,3],[4,5,6]])
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [43]:
# Rank of a matrix

# The rank of a matrix is the maximum number of lineraly indeoendent row
# or column vectors in it, useful in solving systems of linear equations.

# Determine the rank of a matrix representing customer preferences accross
# different product categories.

b=np.array([[1,0,1],[0,1,0],[1,1,1]])
np.linalg.matrix_rank(b)

np.int64(2)

In [49]:
# Determinant of a Matrix

# The determinant of a matrix provides information about the volume
# scaling factor of the linear transformation described by the matrix

# use case: Calculate the determinant of a matrix representing transformation
# operations in 2D space.

c = np.array([[2,1],[4,3]])
np.linalg.det(c)

np.float64(2.0)

In [55]:
# Creating a identitiy matrix

np.eye(2)


array([[1., 0.],
       [0., 1.]])

In [62]:
# Inverse of a matrix

# The inverse of a matrix allows solving linear  equations and finding transformations that
# undo others.

# use case: Find the inverse of a matrix representing a linear transformation
# to undo its effects.

d = np.array([[1,2],[3,4]])
e = np.linalg.inv(d)
e

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [65]:
# Eignevalues and Eignevectors

# Eignevalues and Eignevectors  describe linear transformations by
# indicating directions that remain unchanged by transforamtion and how much they
# are scaled.

# use case: Calculate eigenvalues and eigenvectors of a matrix presenting
# a systems characteristic behaviours.

e = np.array([[2,1],[1,2]])
np.linalg.eig(e)

EigResult(eigenvalues=array([3., 1.]), eigenvectors=array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))