In [5]:
###################### AGENDA #######################

# Fundamentals of NumPy
# NumPy: Array Object
# Attributes of NumPy Arrays
# Arithmetic Operations using NumPy
# Statistical Function in NumPy
# String Functions in NumPy
# NumPy Array Indexing
# Numpy Array Slicing
# Practical usecase at the end of each module - code along
# Knowledge Check.

In [8]:
# Install NumPy

import numpy as np
ar1d = np.array([1,2,3,4,5])      # 1-D array
print(ar1d)
print(type(ar1d))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
# Learn about CLASS and OOPs

In [10]:
ar0d = np.array([1])       # 0-D array
print(type(ar0d), ar0d)

<class 'numpy.ndarray'> [1]


In [11]:
# Define 2-D array

ar2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ar2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
# Define 3-D array  

ar3d = np.array([[[1,2,3,4],[5,6,7,8],[10,20,30,40]]])
print(ar3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [10 20 30 40]]]


In [13]:
# 4-D array is a combination of two 3-D array
# 3-D array is a combination of two 2-D array
# 2-D array is a combination of two 1-D array
# 1-D array is a combination of two 0-D array

In [14]:
# Exercise 1

# 1.Create a 1D array with 5 even numbers

arr1D = np.array([2,4,6,8,10])
print(arr1D)

[ 2  4  6  8 10]


In [15]:
# 2. Create a 2D array with 6 even number (3X2)

arr2D = np.array([[2,4],[6,8],[10,12]])
print(arr2D)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [17]:
# Attributes

print(arr2D.ndim)     # 1. Dimensions      : array.ndim
print(arr2D.shape)    # 2. Shape           : array.shape
print(arr2D.size)    # 3. Size            : array.size      (Total elements in the array)
print(arr2D.dtype)    # 4. Type            : array.dtype
print(arr2D.itemsize) # 5. size            : array.itemsize  (Size of the array)
print(arr2D.data)     # 6. Memory/data     : array.data

2
(3, 2)
6
int64
8


In [24]:
# Reshaping Array

arr2D = np.array([[2,4],[6,8],[10,12]])
# print(arr2D)

newarr = arr2D.reshape(2,3)
print(newarr,(newarr.shape))

[[ 2  4  6]
 [ 8 10 12]] (2, 3)


In [26]:
# Flatten the Array

flatarr = arr2D.flatten()
print(flatarr)

[ 2  4  6  8 10 12]


In [27]:
arr2D

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [30]:
# Transpose Array

trans_array = arr2D.transpose()
print(trans_array)

[[ 2  6 10]
 [ 4  8 12]]


In [33]:
# Generate numbers using 'arange'

np.arange(1,11,2)   #It will generate from 1 to 11 with a space of 2 elements.

array([1, 3, 5, 7, 9])

In [36]:
# Generate Random Numbers with specified shape.
# Values uniformly distributed between 0 and 1.

random_arr = np.random.rand(5,5)
print(random_arr)

[[0.30834627 0.75754451 0.92681992 0.38521787 0.75358488]
 [0.08965854 0.98690011 0.29852479 0.14121842 0.65278277]
 [0.91745078 0.20754424 0.06269833 0.77926712 0.76273971]
 [0.9172433  0.36099685 0.6394476  0.53971508 0.85353065]
 [0.7712884  0.98062691 0.28301446 0.79869685 0.66427037]]


In [47]:
# Creating multidim array using arange.

multi_arr = np.arange(6)
multi_arr = multi_arr.reshape(3,2)
print(multi_arr)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
############## Exercise 1 ###############

# Dimension and Shape
# Create a NumPy array arr1 of shape (3,4) filled with integers from 1 to 12
# Print the number of dimension(ndim) of arr1
# Print the shape of the arr1
# Size and datatype

In [56]:
# arr1 = np.arange(1,13)
# print(arr1)

arr1 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(arr1)

# arr1 = arr1.reshape(3,4)
# print(arr1)

print(arr1.ndim)

print(arr1.shape)

print(arr1.size)

print(arr1.dtype)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3
(1, 3, 4)
12
int64


In [ ]:
################ Exercise 2 ###################

# Flatten the arr1 into 1D array
# Print flatten array
# Transpose function

In [66]:
arr2D = np.array([[2,4],[6,8],[10,12]])

f_arr1 = arr2D.flatten()
print(f_arr1)

t_arr1 = arr2D.transpose()
print(t_arr1)

[ 2  4  6  8 10 12]
[[ 2  6 10]
 [ 4  8 12]]


In [81]:
# Arithmetic operations in array

arr_A = np.array([[1,2,3],[4,5,6]])
arr_B = np.array([[10,20,30],[40,50,600]])

arr_add = np.add(arr_A,arr_B)
print(arr_add)

arr_sub = np.subtract(arr_B,arr_A)
print(arr_sub)

arr_mul = np.multiply(arr_A,arr_B)
print(arr_mul)

arr_div = np.divide(arr_A,arr_B)
print(arr_div)

arr_pow = np.power(arr_A,arr_B)
print(arr_pow)

[[ 11  22  33]
 [ 44  55 606]]
[[  9  18  27]
 [ 36  45 594]]
[[  10   40   90]
 [ 160  250 3600]]
[[0.1  0.1  0.1 ]
 [0.1  0.1  0.01]]
[[                   1              1048576      205891132094649]
 [                   0 -6776596920136667815                    0]]


In [ ]:
################ Exercise 3 ####################
# Question: Perform the following operations using NumPy arrays:

# Add the arrays a = np.array([10,20,30]) and b = np.array([5,10,15])
# Subtract the arrays c = np.array ([[50,40],[30,20]]) and d = np.array([[10,20],[5,15]])
# Multiply the arrays e = np.array([2,4,6]) and f = np.array([3,6,9])
# Divide the array g = np.array([[10,20,30],[40,50,60]]) by h = np.array([2,5,10])
# Compute the power of i = np.array([1,2,3,4]) raised to j = np.array([2,3,4,5])

In [83]:
a = np.array([10,20,30])
b = np.array([5,10,15])
print(np.add(a,b))

[15 30 45]


In [85]:
c = np.array ([[50,40],[30,20]])
d = np.array([[10,20],[5,15]])
print(np.subtract(c,d))

[[40 20]
 [25  5]]


In [86]:
e = np.array([2,4,6])  
f = np.array([3,6,9])
print(np.multiply(e,f))

[ 6 24 54]


In [87]:
g = np.array([[10,20,30],[40,50,60]])
h = np.array([2,5,10])
print(np.divide(g,h))


[[ 5.  4.  3.]
 [20. 10.  6.]]


In [89]:
i = np.array([1,2,3,4]) 
j = np.array([2,3,4,5])
print(np.power(i,j))

[   1    8   81 1024]


In [99]:
# Statistics for Arrays.

arr_stat = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Median
print(np.median(arr_stat))

# Mean
print(np.mean(arr_stat))

# Standart Deviation
print(np.std(arr_stat))

# Variance
print(np.var(arr_stat))

# 75th Percentile
print(np.percentile(arr_stat,75))

5.0
5.0
2.581988897471611
6.666666666666667
7.0


In [107]:
# String Functions on Array

str1 = np.array(["Hello"," World"])
str2 = np.array([" Welcome"," to NumPy"])

In [108]:
# Concatinate Strings(Adding)

str12 = np.char.add (str1 ,str2)
print(str12)

['Hello Welcome' ' World to NumPy']


In [110]:
# SubString replacement

str = ' Hello, how are you!'
print(np.char.replace(str,'Hello','Hi'))

 Hi, how are you!


In [112]:
# String Case conversion

str = "HELLO WORLD"
print(np.char.lower(str))

str1 = 'good morning'
print(np.char.upper(str1))

hello world
GOOD MORNING


In [121]:
# Indexing and Slicing

x = np.array([1,2,3,4,5,6])  #1D Array

print(x[0])
print(x[4])
print(x[1:5])
print(x[-4])
print(x[:6])
print(x[-4:-2])

1
5
[2 3 4 5]
3
[1 2 3 4 5 6]
[3 4]


In [151]:
y = np.array([[1,2,3,4],[5,6,7,8]])   #2D Array

print(y)

print(y[0,1])
print(y[1,3])
print(y[0,-1])
print(y[ :,2])

[[1 2 3 4]
 [5 6 7 8]]
2
8
4
[3 7]


In [174]:
z = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[50,60,70,80]]])   #3D Array
print(np.ndim(z),z)

print(z[0,1,0])
print(z[0,1,:])
print(z[0,1,-1])
print(z[0,1])
print(z[1,])

3 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 20 30 40]
  [50 60 70 80]]]
5
[5 6 7 8]
8
[5 6 7 8]
[[10 20 30 40]
 [50 60 70 80]]


In [175]:
array_1d = np.array([1, 2, 3, 4, 5, 6])

array_2d = np.array([[1, 2, 3], [4, 5, 6]])

array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [194]:
# Print the value of 3rd element of 1D array

print(array_1d[2])

print(array_1d[3]+array_1d[2])

print(array_1d[2:6:2])

3
7
[3 5]


In [183]:
# Print the 3rd element of the 1st row of 2D array

print(array_2d[0,2])

# Print 1st row of the 1element of 3D array

print(array_3d[0,0,0])

# Print 8 from the 3D array

print(array_3d[1,0,1])

3
1
8


In [ ]:
# Practical Exercise: Analyzing Temperature Data

# Scenario: 
# You are a data analyst working with weather data. You have a dataset containing
# a daily temperature record over a month(30 days) for 3 different cities
# City A, City B, City C. Your task is to extract and analyse specifics of this data
# using slicing technique

# Generating data
# import numpy as np

# Generate random temperature data for demonstation purpose
np.random.seed(0) #For producibility
temperature_data = np.random.radiant(15,35, size(30,3))

# Parameters:
# 15: The lower boundary (inclusive) of the random integers to be generated.
# 35: The upper buondary (exclusive) of the random integers to be generated.
# size=(30,3): Specifies the shape of dimensions of the output array, Here it creates
# an array with 30 rows and columns.

In [199]:
# Generate random temperature data for demonstation purpose
np.random.seed(0) #For producibility
temperature_data = np.random.randint(15,35, size=(30,3))
print(temperature_data)

[[27 30 15]
 [18 18 22]
 [24 34 33]
 [19 21 27]
 [16 21 22]
 [29 32 20]
 [28 23 24]
 [34 31 34]
 [20 30 30]
 [15 33 18]
 [32 34 34]
 [34 29 22]
 [15 16 24]
 [15 25 18]
 [26 33 17]
 [15 15 19]
 [20 21 23]
 [32 30 19]
 [24 25 16]
 [16 22 24]
 [18 21 26]
 [29 33 15]
 [29 18 27]
 [25 26 19]
 [21 19 30]
 [18 27 19]
 [23 29 30]
 [18 30 28]
 [31 32 20]
 [24 18 15]]


In [232]:
# Questions:

# Extract the temprature data for the first 10 days for all three cities
# print(temperature_data[:10])
print(temperature_data[:10,0:3])

[[27 30 15]
 [18 18 22]
 [24 34 33]
 [19 21 27]
 [16 21 22]
 [29 32 20]
 [28 23 24]
 [34 31 34]
 [20 30 30]
 [15 33 18]]


In [201]:
# Extract the temperature data for City B for the entire month

print(temperature_data[:,1])

[30 18 34 21 21 32 23 31 30 33 34 29 16 25 33 15 21 30 25 22 21 33 18 26
 19 27 29 30 32 18]


In [235]:
# Extract the temperature data for the last 7 days for City A and City C

print(temperature_data[-7:,[0,2]])  #[0,2] is passed as a list. 
# print(temperature_data[-7:,0])
# print(temperature_data[-7:,2])

[[25 19]
 [21 30]
 [18 19]
 [23 30]
 [18 28]
 [31 20]
 [24 15]]


In [215]:
# Extract the temperature data for the first 5 days and last 5 days of city C

print(temperature_data[:5,2])
print(temperature_data[-5:,2])

[15 22 33 27 22]
[19 30 28 20 15]


In [222]:
# Calculate the average temperature for the first half(15 days) and second half (15 days)
# of the month

half1 = temperature_data[:15, ]
# print(half1)

print(np.mean(half1))

half2 = temperature_data[15:, ]
# print(half2)

print(np.mean(half2))

24.933333333333334
23.08888888888889


In [231]:
a = np.random.randint(1,10, size=(2,5))
# np.random.randint creates random number
# it creates between 1 to 10 
# it creates of shape 2X5

print(a)

[[4 5 2 3 2]
 [5 7 9 3 4]]
